name: Deploy Project

on:
  push:
    branches:
      - main
jobs:
  deploy_back:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Ensure SSH directory exists
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Add SSH known hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Install Dependencies of Back
        working-directory: ./back
        run: npm i

      - name: Build Back
        working-directory: ./back
        run: npx tsc

      - name: Copy Files to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            rm -rf /var/www/personalproject1
            mkdir /var/www/personalproject1
            mkdir /var/www/personalproject1/public
            mkdir /var/www/personalproject1/sessions'
          rsync -avz -e "ssh" ./back/build/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/personalproject1
          rsync -avz -e "ssh" ./back/package.json ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/personalproject1/package.json
          rsync -avz -e "ssh" ./back/public/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/personalproject1/public
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" || {
          echo "nvm.sh not found"
          exit 1
          }
          cd  /var/www/personalproject1
          npm i --production
          echo PORT=3082 > .env
          echo EC2_MYSQL_USER=${{ secrets.EC2_MYSQL_USER }} >> .env
          echo EC2_MYSQL_PASSWORD=${{ secrets.EC2_MYSQL_PASSWORD }} >> .env
          echo EC2_MYSQL_DATABASE=${{ secrets.EC2_MYSQL_DATABASE }} >> .env
          echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> .env
          echo GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }} >> .env
          echo GOOGLE_REDIRECT_OAUTH=${{ secrets.NEXT_PUBLIC_GOOGLE_REDIRECT_OAUTH }} >> .env
          echo FACEBOOK_CLIENT_ID=${{ secrets.FACEBOOK_CLIENT_ID }} >> .env
          echo FACEBOOK_SECRET=${{ secrets.FACEBOOK_SECRET }} >> .env
          echo FACEBOOK_REDIRECT_OAUTH=${{ secrets.NEXT_PUBLIC_FACEBOOK_REDIRECT_OAUTH }} >> .env'

      - name: Start Server
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" || {
          echo "nvm.sh not found"
          exit 1
          }        
          npm install -g pm2          
          pm2 delete personalproject1
          pm2 start /var/www/personalproject1/index.js --name personalproject1'
